	.TIME
	.INSERT "WITNESSFREQ"
	.INSERT "WITNESSDAT"			; DATA IS IN THIS FILE
	.INSERT "MACROS"
	.INSERT "PLACES"
	.INSERT "PEOPLE"
	.INSERT "THINGS"
	.INSERT "SYNTAX"
	.INSERT "CLOCK"
	.INSERT "MAIN"
	.INSERT "PARSER"
	.INSERT "VERBS"
	.INSERT "EVENTS"
	.INSERT "WITNESSSTR"

	.END
